<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.0" />
    <PackageVersion Include="MSTest" Version="4.4.0" />
    <PackageVersion Include="Reqnroll.MSTest" Version="3.3.4" />
  </ItemGroup>

</Project>
